import { StyleSheet } from 'react-native';
import { widthPercentageToDP as wp, heightPercentageToDP as hp } from 'react-native-responsive-screen';

const styles = StyleSheet.create({
  toggle: {
    flexDirection: 'row',
    width: wp('90%'),
    height: hp('8%'),
    justifyContent: 'space-evenly',
    alignSelf: 'center',
    alignItems: 'center',
    marginVertical: 30,
  },
  toggleItemText: {
    color: 'white',
    fontWeight: '500',
    fontSize: wp('5%'),
  },
  selectedToggleText: {
    color: 'white',
    fontWeight: '600',
    textDecorationLine: 'underline',
    fontSize: wp('5%'),
  },
  accountInfoContainer: {
    flex: 1,
    justifyContent: 'space-around',
    alignItems: 'center',
    backgroundColor: 'white',
    alignSelf: 'center',
    marginHorizontal: wp('10%'),
    marginBottom: hp('20%'),
    height: hp('10%'),
    paddingBottom: hp('5%'),
    paddingTop: hp('2%'),
    paddingHorizontal: wp('10%'),
    borderRadius: 10,
  },
  substanceContainer: {
    backgroundColor: 'white',
    alignSelf: 'center',
    justifyContent: 'space-around',
    marginHorizontal: wp('10%'),
    marginBottom: hp('20%'),
    height: hp('10%'),
    paddingHorizontal: wp('10%'),
  },
  sectionHeaderCard: {
    fontSize: wp('6%'),
    fontWeight: '500',
  },
  sectionHeaderMap: {
    fontSize: wp('6%'),
    color: 'black',
    fontWeight: '500',
  },
  sectionHeaderMapResources: {
    fontSize: wp('6%'),
    color: 'white',
    fontWeight: '500',
  },
  paragraph: {
    textAlign: 'center',
  },
  userToken: {
    textAlign: 'center',
    fontSize: wp('4%'),
    fontWeight: '500',
    borderWidth: wp('0.3%'),
    padding: wp('3%'),
  },
  actionButton: {
    backgroundColor: '#28AC45',
    borderRadius: 4,
    paddingVertical: hp('1%'),
    paddingHorizontal: wp('1%'),
    width: wp('40%'),
    justifyContent: 'center',
  },
  actionButtonText: {
    color: 'white',
    fontSize: wp('4%'),
    textAlign: 'center',
  },
  privacyContainer: {
    flex: 1,
    justifyContent: 'space-around',
    alignItems: 'center',
    backgroundColor: 'white',
    alignSelf: 'center',
    marginBottom: hp('12%'),
    height: hp('10%'),
    paddingHorizontal: wp('5%'),
    paddingTop: hp('5%'),
    borderRadius: 10,
    maxWidth: wp('80%'),
  },
  privacyParagraph: {
    fontSize: wp('4%'),
    fontWeight: '400',
    textAlign: 'center',
    color: 'black',
    maxWidth: wp('70%'),
    alignSelf: 'center',
  },
  policyContainer: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'space-evenly',
    maxHeight: hp('60%'),
    width: wp('80%'),
  },
  resourceContainer: {
    flex: 1,
    flexDirection: 'column',
    height: hp('80%'),
    alignItems: 'center',
  },
  resourceList: {
    height: hp('64%'),
    marginTop: hp('3%'),
  },
  resource: {
    flexDirection: 'column',
    justifyContent: 'center',
    width: wp('70%'),
    padding: wp('4%'),
    borderRadius: 7,
    backgroundColor: 'white',
    marginVertical: hp('1%'),
  },
  resourceTitle: {
    textAlign: 'center',
    fontSize: wp('4.5%'),
    fontWeight: '500',
  },
  resourceContact: {
    textAlign: 'center',
    color: '#28AC45',
  },
  resourceContactContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: hp('1%'),
  },
});

export default styles;
